# Generated by Django 5.0.1 on 2024-01-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_episode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='episode',
            name='date',
            field=models.DateField(verbose_name='episode date'),
        ),
        migrations.AddField(
            model_name='anime',
            name='characters',
            field=models.ManyToManyField(to='main_app.character'),
        ),
    ]
